version: "3.9"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "account"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: